import HeaderMinimal from "../components/layout/header-minimal";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <HeaderMinimal />
        {children}
      </body>
    </html>
  );
}
